import LanguageSwitcher from "@/components/LanguageSwitcher";
import { languages } from "@/i18n";
import "@/public/styles/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "HTech Web",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lng: string }>;
}>) {
  const { lng } = await params;

  return (
    <html lang={lng}>
      <body className="h-full w-full relative">
        <div className="absolute top-4 right-4 z-50">
          <LanguageSwitcher />
        </div>

        {children}
      </body>
    </html>
  );
}
