import { languages } from "@/i18n";
import "../globals.css";
import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import Header from "@/common/components/ui/Header";

export const metadata: Metadata = {
  title: "HTech Web",
  description: "Generated by create next app",
};

const beVietnamPro = Be_Vietnam_Pro({
  subsets: ["vietnamese", "latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-be-vietnam-pro",
  display: "swap",
});

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lng: string }>;
}>) {
  const { lng } = await params;

  return (
    <html lang={lng}>
      <body
        className={`${beVietnamPro.variable} font-sans h-full w-full relative`}>
        {/* <Header lng={lng} /> */}
        <Header/>
        {children}
        {/* <Footer lng={lng}/> */}
      </body>
    </html>
  );
}