import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { languages } from "@/i18n";
import "@/public/styles/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "HTech Web",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lng: string }>;
}>) {
  const { lng } = await params;

  return (
    <html lang={lng}>
      <body className="h-full w-full relative">
        
        <Header lng={lng}/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}